### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by johnweslee**
Added detailed steps to clone repository, install mdbook and run the application on localhost

### CODE REVIEW

**Comment by johnweslee** [comment]
Hi @rohansx,
Hope you find this helpful.
PR related to https://github.com/rohansx/web3-security/issues/1

**Review by rohansx — CHANGES_REQUESTED** [review]
could you please add brief description about this repo

**Review by rohansx — APPROVED** [review]
LGTM

**Comment by johnweslee** [comment]
> could you please add brief description about this repo

Done

**Pull request merged**
